Repository url-shorteners/url-shortener, pull requests merged in 2022-10, with the labels that each got.

#2 [config] 초기 파일 생성
  urlShortener/HELP.md
  urlShortener/build.gradle
  urlShortener/build/classes/java/main/com/urlShortener/UrlShortenerApplication.class
  urlShortener/build/resources/main/application.properties
  urlShortener/build/tmp/compileJava/previous-compilation-data.bin
  urlShortener/gradle/wrapper/gradle-wrapper.jar
  urlShortener/gradle/wrapper/gradle-wrapper.properties
  urlShortener/gradlew
  urlShortener/gradlew.bat
  urlShortener/settings.gradle
  urlShortener/src/main/java/com/urlShortener/UrlShortenerApplication.java
  urlShortener/src/main/resources/application.properties
  urlShortener/src/test/java/com/urlShortener/UrlShortenerApplicationTests.java
Labels: config, 승기 작업⭐

#7 gitIgnore 파일을 수정한다.
  .gitignore
Labels: 승기 작업⭐

#6 swagger 설정파일을 추가한다
  urlShortener/build.gradle
Labels: config

#10 Swagger UI에서 보여질 코드 작성
  urlShortener/src/main/java/com/urlShortener/Url/UrlController.java
Labels: feat
